### ISSUE TITLE
UMS module is not expose for browser

### ISSUE THREAD

**Issue by belokonm** [jexia/jexia-sdk-js#165]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
const ums = jexiaSDK.UMSModule() - is not applicable

## Expected behavior
const ums = jexiaSDK.UMSModule() - is not applicable

## Minimal reproduction of the problem with instructions

const ums = jexiaSDK.UMSModule() - is not applicable

## What is the motivation / use case for changing the behavior?
I want to use UMS features in browser. 

## Please tell us about your environment

<pre><code>
SDK version: 4.10.1

Execution Platform Error:

- [ ] NodeJS version XX
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 78
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Operation System:
Linux

Others:

**Comment by jamie-endeavour** [comment]
Hi there 👋 

Have you consulted the documentation for the UMS module? https://docs.jexia.com/ums/#sign-up-a-user I ask this because your syntax looks different to what the documentation is expecting. You have declare a new instance of UMS and then assign that to a variable, which is different to what you are doing here.

E.g.

```js
import { UMSModule } from ‘jexia-sdk-js’;

// Declare new instance
const ums = new UMSModule();

// ...rest of your code
```

If you have tried this and are still getting an error then it might help the team if you can paste your error messages to the issue and update the description to be marked as a bug, the ability to use this module in the browser is already there.

There’s also a Community Discord channel for Jexia, which is probably a better place to post these kind of questions before raising an issue as you are likely to get a quicker response from community members. I don’t have the URL to hand but I’m happy to try and retrieve it when I am next online if you would like it.

I hope this helps!

**Comment by belokonm** [comment]
Hi @jamie-endeavour . Thank you for suggestion was able to interact with User management like 

const jexiaSDK = require("jexia-sdk-js/browser");
const ums = new jexiaSDK.UMSModule() 

working well
